CREATE TABLE SO_Header_Commit(
    [DocNum] [bigint] IDENTITY(1,1) PRIMARY KEY,
    [EntryNum] [nvarchar](max),
    [DraftNum] [bigint],
    [PostingDate] [date],
    [DocDate] [date],
    [CustomerCode] [nvarchar](max),
    [CustomerName] [nvarchar](max),
    [WalkInName] [nvarchar](max),
    [ShippingAdd] [nvarchar](max),
    [TIN] [nvarchar](max),
    [Reference] [nvarchar](max),
    [SCPWDIdNo] [nvarchar](max),
    [Branch] [nvarchar](max),
    [DocStat] [nvarchar](max),
    [BaseDoc] [int],
    [Cash] [nvarchar](max),
	[CreditCard] [nvarchar](max),
    [DebitCard] [nvarchar](max),
    [ODC] [nvarchar](max),
    [PDC] [nvarchar](max),
    [OnlineTransfer] [nvarchar](max),
    [OnAccount] [nvarchar](max),
    [COD] [nvarchar](max),
    [TotalAmtBefTax] [float],
    [TotalTax] [float],
    [TotalAmtTax] [float],
    [SCPWDDiscTotal] [float],
    [TotalAmtDue] [float],
    [Remarks] [nvarchar](max),
    [CreatedBy] [nvarchar](max),
    [DateCreated] [date],
    [UpdatedBy] [bigint],
    [DateUpdated] [date],
    [SalesCrew] [nvarchar](max),
    [ForeignName] [nvarchar](max)
)
